module.exports = [{
  name: 'Button',
  icon: 'border',
  displayName: '按钮',
  isFormControl: false
}, {
  name: 'Radio',
  icon: 'tablet',
  displayName: '单选框',
  isFormControl: true
}, {
  name: 'Checkbox',
  icon: 'check-square',
  displayName: '多选框',
  isFormControl: true
}, {
  name: 'Switch',
  icon: 'switcher',
  displayName: '开关',
  isFormControl: true
}, {
  name: 'Cascader',
  icon: 'diff',
  displayName: '级联选择',
  isFormControl: true
}, {
  name: 'DatePicker',
  icon: 'calendar',
  displayName: '日期选择',
  isFormControl: true
}, {
  name: 'TimePicker',
  icon: 'clock-circle',
  displayName: '时间选择',
  isFormControl: true
}, {
  name: 'Slider',
  icon: 'column-width',
  displayName: '滑动输入条',
  isFormControl: true
}, {
  name: 'Affix',
  icon: 'heat-map',
  displayName: '固钉',
  isFormControl: false
}, {
  name: 'Breadcrumb',
  icon: 'tag',
  displayName: '面包屑',
  isFormControl: false
}, {
  name: 'Dropdown',
  icon: 'down-square',
  displayName: '下拉菜单',
  isFormControl: false
}, {
  name: 'Menu',
  icon: 'menu',
  displayName: '导航菜单',
  isFormControl: false
}, {
  name: 'Pagination',
  icon: 'copy',
  displayName: '分页',
  isFormControl: false
}, {
  name: 'PageHeader',
  icon: 'radius-upleft',
  displayName: '页头',
  isFormControl: false
}, {
  name: 'Steps',
  icon: 'arrow-right',
  displayName: '步骤条',
  isFormControl: false
}]
